# -*- coding: utf-8 -*-
"""Prak Algo 7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kvdvA9WeJZJ1HddCWSEFy2Sk4L-iUrbm
"""

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

def menghitung_faktorial(x):
    if x < 0:
        return
    elif x == 0 or x == 1:
        return 1
    else:
        hasil = 1
        for i in range(2, x + 1):
            hasil *= i
        return hasil
bilangan = int(input("nilai: "))
print(f"Faktorial dari {bilangan} adalah {menghitung_faktorial(bilangan)}")

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

def hitung_vokal_dan_konsonan(kalimat):
    jumlah_vokal = 0
    jumlah_konsonan = 0
    kalimat = kalimat.lower()
    for karakter in kalimat:
        if karakter.isalpha():
           if karakter in 'aeiou':
              jumlah_vokal += 1
           else:
                jumlah_konsonan += 1
    print(f"Jumlah huruf vokal: {jumlah_vokal}")
    print(f"Jumlah huruf konsonan: {jumlah_konsonan}")
kalimat_input = input("Masukkan kalimat: ")
hitung_vokal_dan_konsonan(kalimat_input)

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

def kubik_angka(angka):
    return angka ** 3

def cek_habis_dibagi_tiga(angka):
    if angka % 3 == 0:
        hasil_kubik = kubik_angka(angka)
        return hasil_kubik
    else:
        return False
angka_input = int(input("Masukkan nilai: "))
hasil_cek = cek_habis_dibagi_tiga(angka_input)
if hasil_cek is not False:
    print(f"Hasil nya adalah: {hasil_cek}")
else:
    print(f"false")